### PR TITLE
Error bars for `hCLsExp`

### LINKED ISSUE #210: Uncertainties on expected CLs (relevant for advanced interpolation)
The uncertainties on hCLsExp appear to be the default, unlike the uncertainties on hCLsFreq, which are calculated explicitly. Presumably these incorrect uncertainties are used when fitting a pol2 to the expected points to perform interpolation. Would it be possible to put the correct uncertainties on this histogram?

### PR DESCRIPTION
**Pull request by tmombaecher**
adding error bars to the `hCLsExp` to improve the interpolation for the expected limit calculations.
Fixes #210

### CODE REVIEW

File: core/src/MethodDatasetsPluginScan.cpp [hunk 1]
```diff
@@ -763,6 +763,7 @@ void MethodDatasetsPluginScan::readScan1dTrees(int runMin, int runMax, TString f
 
         // //ideal method, but prone to fluctuations
         hCLsExp->SetBinContent   ( i, TMath::Min( quantiles_cls[2] , 1.) );
+        hCLsExp->SetBinError   ( i, sq((1.-TMath::Min( quantiles_cls[2] , 1.))*TMath::Min( quantiles_cls[2] , 1.)/sampledBValues[i].size()) );
```
Comment (fionnbishop) [inline core/src/MethodDatasetsPluginScan.cpp:766]: I think it should be sqrt instead of sq

Comment (tmombaecher) [reply core/src/MethodDatasetsPluginScan.cpp]: good point. That was a square. Fixed it.

**Comment by matthewkenzie** [comment]
If you're both happy then I'm happy. Thanks @fionnbishop (and @tmombaecher for implementing)
